### PR TITLE
Changing cleaning code for later version of R compatibility

### PR DESCRIPTION
**Pull request by opiemartin**
Hi Alex,

In the most recent commit there are the changes to the R cleaning code I originally forked. If it is not possible to ignore the other commits I will try and work out how to add them to a different branch.

### CODE REVIEW

**Comment by acpuchades** [comment]
Hi @opiemartin I've already integrated all the compatibility changes and I also integrated your files.
I'm working on a CONTRIBUTING.md with instructions on how to avoid file conflicts per-site.

I'll keep this PR open until you confirm that everything is working for you with the latest changes.

**Comment by opiemartin** [comment]
Thanks Alex, have had a quick look and will try updating my repository based on this new structure probably tomorrow.

I think some of Ruben's files are a bit duplicated - he split his initial file into data cleaning and data analysis but kept the original file in. We (question 2 analysts) have a meeting tomorrow afternoon and I can ask him for the details then if that's ok? It might mean deleting a couple of files to clean it up.

Also the rmcf folder is really question 1 - this is code written by Rob McFarlane who has access to my repository forked from yours and we are working on q1 together.

The other thing I wanted your opinion on is whether I should keep my own fork, this is used by myself, Rob, Daphne and Ruben or should we abandon that and use your repository directly? I think its probably a case of just knowing what we are doing rather than there being a right or wrong way but you have more insight than me!

Kind regards,
Sarah

**Comment by acpuchades** [comment]
Hi Sarah,

My initial idea was that every interested site would fork my repo and use it as a template but after that it would become an independent project.

However, I see more and more cases where refinements to base files (such as Ruben’s ALSFRS-R data cleaning code) are required for every other site and merging back those changes to forked repos would quickly become painful in the long term.

That’s why this weekend I’ve been working on adopting a project structure where every question gets its own src/ and output/ folders and so file conflicts are completely avoided.

That would allow us to share the same repository (could use mine), using branches prefixed with question-specific prefixes and merging back to the master branch when changes are ready.

I’m writing a CONTRIBUTING.md file that will be incorporated to the repo during this week with instructions to make the document every step of the process.Please make me know what you think.

Regards,

AC

**Comment by opiemartin** [comment]
Thanks Alex I think that makes sense to me, I'm happy to test the process flow and review the contributing.md file if that's helpful.

Best wishes,
Sarah


Sarah Opie-Martin

Data Scientist MND Register for England, Wales and Northern Ireland
________________________________

**Comment by opiemartin** [comment]
Hi Alex,

I am working on precision tasks today and just thinking about the file structure – did you mean it will be organised like this?

|-- acpuchades/
                |-- precision-als-task/
                                |-- src/
                                                |-- ext/ <-- *cleaning files including Ruben's ALSFRSR code?*
                                                |-- q2/
                                                                |-- src/ <-- *modelling/summary code?*
                                                                |-- out/ <-- *graphs/output tables?*
                                                |-- q3/
                                                                |-- src/
                                                                |-- out/
                                                |-- qc/
                                                |-- rmcf/
                                                                |-- src/
                                                                |-- out/
                                |-- doc/
                                |-- extra/

Would I fork the whole thing but only be expected to update folders related to the questions I’m working on?

Also, the data isn’t public but should it be in a folder /data?

Best wishes,
Sarah

**Comment by opiemartin** [comment]
Hi Alex,

I made an update to the ext_main code to try and clean the diagnoses a bit, although I’m not sure whether all the choices are appropriate.

Also, I wondered if I should try and integrate Ruben’s alsfrsr cleaning code into you ext_alsfrsr script or is this something that you might plan to do with the repository structure changes?

Anything I can do to be helpful with this please let me know… At the moment I am updating my forked version from my local but haven’t adopted your new structure.

Best wishes,
Sarah

**Comment by acpuchades** [comment]
Hi Sarah,

> I am working on precision tasks today and just thinking about the file structure – did you mean it will be organised like this?

The code structure would be like:
- **/data:** Input data files should be here. Not tracked by Git.
- **/output**: Generated files are stored here. Not tracked by Git.
- **/doc**: Documentation related to the project.
- **/extra**: Files not covered elsewhere.
- **/src**: Source code files
    - **./ext**: Common code for all subtasks containing parsed and cleaned data as well as utility functions.
    - **./qc**: Quality control scripts.
    - **./qX**: Subfolders specific for each extant subtask.

Instructions on how to set up the project to get started will also be included in the CONTRIBUTING.md file.
Ideally, source files from subtasks should only reference code in the same folder and /src/ext, and output files only within their own /output subfolder. Branches should restrict their changes within one src subfolder. PR affecting one question will be automatically merged after approval from all sites responsible for that question. Changes to /src/ext will be reviewed on a case by case, the expectation being that they should be backwards-compatible (essentially means append-only or bug fixes).

> Also, I wondered if I should try and integrate Ruben’s alsfrsr cleaning code into you ext_alsfrsr script or is this something that you might plan to do with the repository structure changes?

I think I already did (do you mean [this code](https://github.com/acpuchades/precisionals-extant-task/blob/141c52711e4192e46684d0ca1399b92e18202642/src/ext/alsfrs.r#L7)? The Q3 code relied on the original column names in ext_alsfrs and any other subtasks already using ext_alsfrs will benefit from Ruben's fixes.

> Anything I can do to be helpful with this please let me know… At the moment I am updating my forked version from my local but haven’t adopted your new structure.

If you haven't changed any of the ext/ files, maybe it's easier (also as a way of testing this worklow) to just clone my repo again, create a new branch, overwrite your files with the updated ones and try to merge back that branch. Let's see how it goes.

**Comment by acpuchades** [comment]
I've just pushed a CONTRIBUTING.md file with instructions on how to set up the project as well as a suggested workflow.

**Comment by opiemartin** [comment]
Thanks Alex, sorry I didn't see the code you'd made but it looks really great. I've gone through the files in my repo and since I sent the pull request to you there have been two changes to files in my repository.

I've saved that code in test files (and actually created a local copy of my repository as it currently is under a new name). If I 'sync fork' am I right in understanding that your new structure will override mine?

Best wishes,
Sarah

Sarah Opie-Martin
Data Scientist - MND Register for England, Wales and Nothern Ireland

**Comment by opiemartin** [comment]
Since then I've just updated my repo and gone through your suggested workflow - seems fine to me I think - let me know if I've followed correctly.

Best wishes,
Sarah

Sarah Opie-Martin
Data Scientist - MND Register for England, Wales and Nothern Ireland


From: Sarah Martin
Sent: 19 April 2023 09:47
To: acpuchades/precisionals-extant-task ***@***.***>; acpuchades/precisionals-extant-task ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [acpuchades/precisionals-extant-task] Changing cleaning code for later version of R compatibility (PR #1)

Thanks Alex, sorry I didn't see the code you'd made but it looks really great. I've gone through the files in my repo and since I sent the pull request to you there have been two changes to files in my repository.

I've saved that code in test files (and actually created a local copy of my repository as it currently is under a new name). If I 'sync fork' am I right in understanding that your new structure will override mine?

Best wishes,
Sarah

Sarah Opie-Martin
Data Scientist - MND Register for England, Wales and Nothern Ireland

**Pull request closed without merging**
