### PR TITLE
Q1 updating

### PR DESCRIPTION
**Pull request by opiemartin**
Want to sync with main fork

### CODE REVIEW

**Review by acpuchades — CHANGES_REQUESTED** [review]
Hi @opiemartin, all the q1/ files look good to me.

Regarding ext/common.r, I saw you changed the default data path to "./NEWPALS", would it not be possible to use ./data or adjust your local PALS_EXTANT_DATADIR environment variable instead? I'm afraid this change could break someone else's setup. Please make me know if that would work for you.

If it was not an intended change, you can revert the changes made to ext/common.r and I'll happily merge your PR asap.

**Comment by opiemartin** [comment]
H Alex,

Thanks let me know if that can be done now? It seems to have resolved the issues but I'm not sure if I need to press something else to send it over to you!

Thanks :)

Sarah

**Comment by acpuchades** [comment]
Everything is fine now, I just merged your PR 😊 

Btw I saw there's another PR from you still open, are those changes already part of this PR?

**Comment by opiemartin** [comment]
Thanks very much 😊 – yes they should be the same ones.

I’ll be committing a large change to the Q2 files with Ruben’s code that references version 2 of the alsfrsr data. Should I go through and update the alsfrsr function script you wrote as well? That is out of the Q specific files so I wasn’t sure whether to leave it or not.

Sarah

Sarah Opie-Martin
Data Scientist – MND Register for England, Wales and Nothern Ireland

**Comment by opiemartin** [comment]
Oh sorry – I think the one that is still open is for the main branch.  I opened one for Q1 and the main one

Best wishes,
Sarah

Sarah Opie-Martin
Data Scientist – MND Register for England, Wales and Nothern Ireland

**Comment by opiemartin** [comment]
Also – sorry to keep replying but I’m not sure which branch Rob has been working on. I’m meeting him tomorrow but it might be better to solve the pull request then. I can cancel it if it’s easier!

Best wishes,
Sarah

Sarah Opie-Martin
Data Scientist – MND Register for England, Wales and Nothern Ireland

**Comment by acpuchades** [comment]
Hi Sarah,

Okay then, I'll close the other PR as those changes are merged already. 

Regarding the new PR, if the changes to ext/ files are somehow tied to the q2/ changes it's okay to include them together (just please if you can, remember to ’git pull’ the most recent changes because there's been quite some changes to ext/alsfrs.r from me in the last week).

Cheers,

AC

**Comment by opiemartin** [comment]
Thanks Alex, I've just checked that.

I had also put together some code for working out the delta ALSFRSR but in the analysis_file.r I have checked and we get mostly the same cut offs, but as well as excluding the premorbid by months from onset being > 0 , I also excluded people with an ALSFRSR score of 48 at baseline in the assumption that is also premorbid but it makes a very small difference to the cut off value - there were about 60 people for whom this was the case.

I was planning to discuss the delta and the longitudinal alsfrsr cutoffs on Friday in the summary - will you be presenting the time to event by delta cut off?

Best wishes,
Sarah

Sarah Opie-Martin
Data Scientist - MND Register for England, Wales and Nothern Ireland

**Pull request merged**
